name: Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm GitHub runner works
        run: |
          echo "GitHub-hosted runner is working."
          uname -a
          python --version
