name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 mins

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Calculate Experience and Level
        id: calc
        run: |
          COMMITS=$(git rev-list --count HEAD)
          XP=$((COMMITS * 10))
          LEVEL=$((XP / 100))
          echo "commits=$COMMITS" >> $GITHUB_ENV
          echo "xp=$XP" >> $GITHUB_ENV
          echo "level=$LEVEL" >> $GITHUB_ENV
        
      - name: Update README
        run: |
          sed -i "s/Level:.*/Level: ${{ env.level }}/" README.md
          sed -i "s/Total Experience:.*/Total Experience: ${{ env.xp }} EXP/" README.md
          
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest stats"
          git push
